### ISSUE TITLE
Please add a CI to generate standalone binaries

### ISSUE THREAD

**Issue by eugenesvk** [dj95/kdl-fmt#1]
**Is your feature request related to a problem? Please describe.**
Having to compile the binary is a bit onerous

**Describe the solution you'd like**
Having a standalone downloadable binary in releases

**Additional context**
N/a

**Comment by dj95** [comment]
Hi and thanks a lot for the feature request.

I've implemented the release workflow now and create a new release, as soon as I've documented the `.kdl-fmt.kdl`.

**Comment by eugenesvk** [comment]
Thanks, is Windows not supported?

**Comment by dj95** [comment]
Unfortunately I'm not familiar with building rust on Windows and have no way to test it.

But I would be happy if someone could help me with this.

**Comment by eugenesvk** [comment]
Maybe just add it to the workflow matrix and see if it builds?

**Comment by dj95** [comment]
That might build the binaries, but I cannot verify if they work properly. For macOS and Linux I have options, but unfortunately not for Windows.

Potentially there could be bugs within file path handling.

**Comment by eugenesvk** [comment]
I could try it for checking doc validity as I'm using another binary for that.

(btw, you can as also run tests in CI on Win with any paths you like)
